import '@/styles/globals.css';

import type { ChildrenProps } from '@/types';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
