import '@/styles/globals.css';

import { Inter } from 'next/font/google';
import Link from 'next/link';

import MainFooter from '@/components/Footer';
import Header from '@/components/Header';
import type { ChildrenProps } from '@/types';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'optional',
});

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-full flex flex-col justify-between`}
      >
        <Header>
          <header className="px-8 py-8 flex justify-between bg-gray-900 text-violet-50">
            <Link href="/">
              <span>Home</span>
            </Link>
            <Link href="/login">
              <span>Login</span>
            </Link>
          </header>
        </Header>
        <section className="flex-1">{children}</section>
        <MainFooter />
      </body>
    </html>
  );
}
